# Generated by Django 4.2.5 on 2023-09-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitableplace',
            old_name='latin',
            new_name='latitude',
        ),
        migrations.RemoveField(
            model_name='visitableplace',
            name='zotude',
        ),
    ]
