# Generated by Django 4.1.1 on 2023-09-24 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_latin_visitableplace_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.visitableplace'),
        ),
    ]
