# Generated by Django 4.1.1 on 2023-09-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_comment_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longtude', models.FloatField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='hotels/images')),
            ],
        ),
        migrations.RenameField(
            model_name='visitableplace',
            old_name='regione',
            new_name='region',
        ),
        migrations.AlterField(
            model_name='visitableplace',
            name='latitude',
            field=models.FloatField(max_length=255),
        ),
    ]
