# Generated by Django 4.1.1 on 2023-09-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_hotel_rename_regione_visitableplace_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteReccomendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
