# Generated by Django 4.1.1 on 2023-09-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_damagereport_sitereccomendation_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/images')),
            ],
        ),
        migrations.AddField(
            model_name='visitableplace',
            name='image',
            field=models.ManyToManyField(related_name='images', to='places.placephoto'),
        ),
    ]
