# Generated by Django 4.1.1 on 2023-09-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_visitableplace_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitableplace',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
