# Generated by Django 4.1.1 on 2023-09-26 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0007_damagereport_sitereccomendation_image_and_more'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_date', models.TextField()),
                ('description', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('destination_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.visitableplace')),
                ('visitors', models.ManyToManyField(related_name='group_tour', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
