# Generated by Django 4.1.1 on 2023-09-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_grouptour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptour',
            name='tour_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
